# server
server:
  port: 8080
  servlet:
    context-path: /simple
  connection-timeout: 0
  tomcat:
    uri-encoding: UTF-8

# spring
spring:
  # datasource
  datasource:
    # 驱动配置信息
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver

    # 连接池的配置信息
    # 配置监控统计拦截的filters,去掉后监控页面sql将无法统计,'wall'用于防火墙
    filters: stat,wall,log4j
    # 最大活跃数
    maxActive: 20
    # 初始化数量
    initialSize: 1
    # 最大连接等待超时时间
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select version()
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 是否缓存preparedStatement,也就是PSCache
    # poolPreparedStatements: true
    # 打开PSCache,并指定每个连接PSCache大小,当大于0时,poolPreparedStatements自动触发修改为true
    maxOpenPreparedStatements: 20

  # redis
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    # 连接超时时间
    timeout: 10000
    jedis:
      pool:
        # 最大连接数
        max-active: 8
        # 最大阻塞等待时间(负数表示没限制)
        max-wait: 100000
        # 最大空闲
        max-idle: 10
        # 最小空闲
        min-idle: 0

  # http
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8

  # servlet
  servlet:
    multipart:
      enabled: true
      max-file-size: 2048MB
      max-request-size: 2048MB
      location: G://tomcat/temp/file

# 系统配置参数
sys:
  name: simple  #系统名称
  code: simple  #系统编码
  enableAUZ: false  #是否开启权限验证
  showIp: true  #登录显示IP地址
  password: 123456  #系统重置登录密码
  cleanLoginInfo: true  #退出登录是否清除当前登录信息缓存

# jwt
jwt:
  issuer: chendreaming@126.com  #jwt发行者
  base64Secret: VHVubmVsJTIwT2YlMjBMb3Zl  #jwt基础64位秘钥
  webLifecycle: 864000  #jwt web端作用时间:秒(这里为10天)
  webUpdateInterval: 86400  #jwt web更新间隔:秒(这里为1天)
  appLifecycle: 864000  #jwt app端作用时间:秒(这里为10天)
  appUpdateInterval: 86400  #jwt app更新间隔:秒(这里为1天)
  enableRenew: true  #开启自动令牌续权
  antiHijack: true  #开启令牌反劫持

# ftp
ftp:
  host: 192.168.10.64
  port: 21
  user: jnzk
  password: jnzk
  path: /home/jnzk/apache-tomcat-8.5.31/webapps/jnzk/
  url: http://192.168.10.64:8080/jnzk

# 日志
logging:
  config: classpath:logback-spring.xml

# mybatis
mybatis:
  config-location: classpath:mybatis-config.xml

# alipay
alipay:
  serveUrl: https://openapi.alipay.com/gateway.do
  appId:
  storeId:
  appPrivateKey:
  alipayPublicKey:
  dataFormat: json
  signType: RSA2
  notifyUrl:
  qrCodeImgUrl:

#短信配置参数(阿里云)
sms:
  verifyTimeOut: 60  #短信验证码时效:秒
  timeOut: 10000  #短信系统超时时间
  accessKeyId:   #开发者自己的AK(在阿里云访问控制台寻找)
  accessKeySecret:    #开发者自己的秘钥
  signName:   #签名
  tempCode:   #短信模板code